export const data=
     [
        {
            "PROPOSAL_NUMBER": "PCLP1006001180227148",
            "POLICY_NUMBER": "CLP1006001180227148",
            "ISSUE_DATE": "15-05-2018",
            "MATURITY_DATE": "15-05-2028",
            "STATUS": "DEATH",
            "PRODUCT": "CHILD LIFELINE PLUS",
            "CLIENT": "KWABENA AGADZI",
            "PREMIUM": "24",
            "Date_of_Birth": "15-03-1990",
            "Gender": "Male",
            "Marital_Status": "Single",
            "Phone_Number": "0245678590",
            "ID_No": "GHA-4525669954-545",
            "ID_Type": "Ghana Card",
            "Residential_Address": "123 Main St, Accra, Ghana",
            "Postal_Address": "P.O. Box 123, Accra, Ghana",
            "Email": "kwabena.agadzi@example.com",
            "Occupation": "Teacher",
            "Policy_Term": "10 years",
            "Sum_Assured": "10000",
            "Payment_Frequency": "Monthly"
        },
        {
            "PROPOSAL_NUMBER": "PWMP1006001070227115",
            "POLICY_NUMBER": "WMP1006001070227115",
            "ISSUE_DATE": "15-11-2007",
            "MATURITY_DATE": "15-11-2010",
            "STATUS": "MATURED",
            "PRODUCT": "WEALTH MASTER PLAN",
            "CLIENT": "KWABENA AGADZI",
            "PREMIUM": "40",
            "Date_of_Birth": "15-03-1990",
            "Gender": "Male",
            "Marital_Status": "Single",
            "Phone_Number": "0245678590",
            "ID_No": "GHA-4525669954-545",
            "ID_Type": "Ghana Card",
            "Residential_Address": "45 Sunshine Ave, Kumasi, Ghana",
            "Postal_Address": "P.O. Box 456, Kumasi, Ghana",
            "Email": "kwabena.agadzi@example.com",
            "Occupation": "Engineer",
            "Policy_Term": "3 years",
            "Sum_Assured": "15000",
            "Payment_Frequency": "Quarterly"
        },
        {
            "PROPOSAL_NUMBER": "PWPP1005001240227148",
            "POLICY_NUMBER": null,
            "ISSUE_DATE": "08-10-2024",
            "MATURITY_DATE": "08-10-2028",
            "STATUS": "DRAFT",
            "PRODUCT": "WEALTH MASTER PLUS",
            "CLIENT": "KWABENA AGADZI",
            "PREMIUM": "100",
            "Date_of_Birth": "15-03-1990",
            "Gender": "Male",
            "Marital_Status": "Single",
            "Phone_Number": "0245678590",
            "ID_No": "GHA-4525669954-545",
            "ID_Type": "Ghana Card",
            "Residential_Address": "78 Market Rd, Cape Coast, Ghana",
            "Postal_Address": "P.O. Box 789, Cape Coast, Ghana",
            "Email": "kwabena.agadzi@example.com",
            "Occupation": "Banker",
            "Policy_Term": "4 years",
            "Sum_Assured": "20000",
            "Payment_Frequency": "Bi-Annually"
        },
        {
            "PROPOSAL_NUMBER": "PPWP1005001240227148",
            "POLICY_NUMBER": null,
            "ISSUE_DATE": "08-10-2024",
            "MATURITY_DATE": "08-10-2028",
            "STATUS": "SURRENDERED",
            "PRODUCT": "PHOBIA WEALTH MASTER",
            "CLIENT": "KWABENA AGADZI",
            "PREMIUM": "52",
            "Date_of_Birth": "15-03-1990",
            "Gender": "Male",
            "Marital_Status": "Single",
            "Phone_Number": "0245678590",
            "ID_No": "GHA-4525669954-545",
            "ID_Type": "Ghana Card",
            "Residential_Address": "14 Freedom St, Tamale, Ghana",
            "Postal_Address": "P.O. Box 1010, Tamale, Ghana",
            "Email": "kwabena.agadzi@example.com",
            "Occupation": "Doctor",
            "Policy_Term": "5 years",
            "Sum_Assured": "25000",
            "Payment_Frequency": "Annually"
        },
        {
            "PROPOSAL_NUMBER": "PPCL1005001220227148",
            "POLICY_NUMBER": "PCL1005001220227148",
            "ISSUE_DATE": "15-09-2022",
            "MATURITY_DATE": "14-09-2032",
            "STATUS": "CANCELLED",
            "PRODUCT": "PHOBIA CHILD EDUCATION",
            "CLIENT": "KWABENA AGADZI",
            "PREMIUM": "213",
            "Date_of_Birth": "15-03-1990",
            "Gender": "Male",
            "Marital_Status": "Single",
            "Phone_Number": "0245678590",
            "ID_No": "GHA-4525669954-545",
            "ID_Type": "Ghana Card",
            "Residential_Address": "29 National Ave, Takoradi, Ghana",
            "Postal_Address": "P.O. Box 2323, Takoradi, Ghana",
            "Email": "kwabena.agadzi@example.com",
            "Occupation": "Accountant",
            "Policy_Term": "10 years",
            "Sum_Assured": "30000",
            "Payment_Frequency": "Monthly"
        },
        {
            "PROPOSAL_NUMBER": "PSUH1005001220227152",
            "POLICY_NUMBER": "SUH1005001240227152",
            "ISSUE_DATE": "01-02-2021",
            "MATURITY_DATE": "01-02-2031",
            "STATUS": "LAPSED",
            "PRODUCT": "SUPREME HOMECALL PLAN",
            "CLIENT": "AMA OKAI",
            "PREMIUM": "95",
            "Date_of_Birth": "23-08-1987",
            "Gender": "Female",
            "Marital_Status": "Married",
            "Phone_Number": "0245987624",
            "ID_No": "GHA-2345629990-345",
            "ID_Type": "Ghana Card",
            "Residential_Address": "99 Ridgeway St, Accra, Ghana",
            "Postal_Address": "P.O. Box 1024, Accra, Ghana",
            "Email": "ama.okai@example.com",
            "Occupation": "Pharmacist",
            "Policy_Term": "10 years",
            "Sum_Assured": "30000",
            "Payment_Frequency": "Monthly"
        },
        {
            "PROPOSAL_NUMBER": "PMFP1006001250227153",
            "POLICY_NUMBER": "MFP1006001230227153",
            "ISSUE_DATE": "25-04-2020",
            "MATURITY_DATE": "25-04-2030",
            "STATUS": "ACTIVE",
            "PRODUCT": "MASTER FAMILY PLAN",
            "CLIENT": "KOFI MENSAH",
            "PREMIUM": "135",
            "Date_of_Birth": "15-05-1992",
            "Gender": "Male",
            "Marital_Status": "Married",
            "Phone_Number": "0245432109",
            "ID_No": "GHA-9876543456-789",
            "ID_Type": "Ghana Card",
            "Residential_Address": "10 Oakwood Dr, Kumasi, Ghana",
            "Postal_Address": "P.O. Box 2345, Kumasi, Ghana",
            "Email": "kofi.mensah@example.com",
            "Occupation": "Electrician",
            "Policy_Term": "10 years",
            "Sum_Assured": "35000",
            "Payment_Frequency": "Bi-Annually"
        },
        {
            "PROPOSAL_NUMBER": "PSYP1006001260227154",
            "POLICY_NUMBER": "SYP1006001230227154",
            "ISSUE_DATE": "10-09-2021",
            "MATURITY_DATE": "10-09-2031",
            "STATUS": "ACTIVE",
            "PRODUCT": "YOUTH ADVANTAGE PLAN",
            "CLIENT": "SARAH KWARTENG",
            "PREMIUM": "75",
            "Date_of_Birth": "30-07-1998",
            "Gender": "Female",
            "Marital_Status": "Single",
            "Phone_Number": "0243123456",
            "ID_No": "GHA-5647382910-123",
            "ID_Type": "Ghana Card",
            "Residential_Address": "44 Blossom St, Sunyani, Ghana",
            "Postal_Address": "P.O. Box 3456, Sunyani, Ghana",
            "Email": "sarah.kwarteng@example.com",
            "Occupation": "Software Developer",
            "Policy_Term": "10 years",
            "Sum_Assured": "25000",
            "Payment_Frequency": "Quarterly"
        },
        {
            "PROPOSAL_NUMBER": "PLCP1005001270227155",
            "POLICY_NUMBER": "LCP1005001230227155",
            "ISSUE_DATE": "01-07-2017",
            "MATURITY_DATE": "01-07-2027",
            "STATUS": "DEATH",
            "PRODUCT": "LIFECOVER PLAN",
            "CLIENT": "JOHN DOE",
            "PREMIUM": "210",
            "Date_of_Birth": "19-04-1980",
            "Gender": "Male",
            "Marital_Status": "Divorced",
            "Phone_Number": "0241230987",
            "ID_No": "GHA-6789043212-432",
            "ID_Type": "Ghana Card",
            "Residential_Address": "12 Kingsway Ave, Ho, Ghana",
            "Postal_Address": "P.O. Box 6543, Ho, Ghana",
            "Email": "john.doe@example.com",
            "Occupation": "Business Owner",
            "Policy_Term": "10 years",
            "Sum_Assured": "60000",
            "Payment_Frequency": "Monthly"
        },
        {
            "PROPOSAL_NUMBER": "PHCP1005101270227156",
            "POLICY_NUMBER": "HCP1005101230227156",
            "ISSUE_DATE": "10-10-2019",
            "MATURITY_DATE": "10-10-2029",
            "STATUS": "ACTIVE",
            "PRODUCT": "HOMEMAKERS PLAN",
            "CLIENT": "AMA BAAH",
            "PREMIUM": "85",
            "Date_of_Birth": "10-10-1990",
            "Gender": "Female",
            "Marital_Status": "Single",
            "Phone_Number": "0242112233",
            "ID_No": "GHA-4556789000-567",
            "ID_Type": "Ghana Card",
            "Residential_Address": "45 Queens Rd, Cape Coast, Ghana",
            "Postal_Address": "P.O. Box 6789, Cape Coast, Ghana",
            "Email": "ama.baah@example.com",
            "Occupation": "Entrepreneur",
            "Policy_Term": "10 years",
            "Sum_Assured": "20000",
            "Payment_Frequency": "Quarterly"
        },
        {
            "PROPOSAL_NUMBER": "PLAP1005201280227157",
            "POLICY_NUMBER": "LAP1005201230227157",
            "ISSUE_DATE": "05-05-2018",
            "MATURITY_DATE": "05-05-2028",
            "STATUS": "ACTIVE",
            "PRODUCT": "LIFECOVER ADVANCE PLAN",
            "CLIENT": "KOJO APPIAH",
            "PREMIUM": "90",
            "Date_of_Birth": "12-12-1983",
            "Gender": "Male",
            "Marital_Status": "Married",
            "Phone_Number": "0247654321",
            "ID_No": "GHA-1236547890-456",
            "ID_Type": "Ghana Card",
            "Residential_Address": "78 Liberty Rd, Bolgatanga, Ghana",
            "Postal_Address": "P.O. Box 1122, Bolgatanga, Ghana",
            "Email": "kojo.appiah@example.com",
            "Occupation": "Civil Engineer",
            "Policy_Term": "10 years",
            "Sum_Assured": "50000",
            "Payment_Frequency": "Annually"
        },
        {
            "PROPOSAL_NUMBER": "PSCP1005301290227158",
            "POLICY_NUMBER": "SCP1005301230227158",
            "ISSUE_DATE": "10-11-2017",
            "MATURITY_DATE": "10-11-2027",
            "STATUS": "SURRENDERED",
            "PRODUCT": "SENIOR CITIZEN PLAN",
            "CLIENT": "MABEL ANKRAH",
            "PREMIUM": "150",
            "Date_of_Birth": "15-06-1958",
            "Gender": "Female",
            "Marital_Status": "Widowed",
            "Phone_Number": "0241122334",
            "ID_No": "GHA-9876545678-901",
            "ID_Type": "Ghana Card",
            "Residential_Address": "88 Heritage St, Accra, Ghana",
            "Postal_Address": "P.O. Box 8976, Accra, Ghana",
            "Email": "mabel.ankrah@example.com",
            "Occupation": "Retired Nurse",
            "Policy_Term": "10 years",
            "Sum_Assured": "10000",
            "Payment_Frequency": "Annually"
        },
        {
            "PROPOSAL_NUMBER": "PMWP1005301300227159",
            "POLICY_NUMBER": "MWP1005301230227159",
            "ISSUE_DATE": "20-03-2019",
            "MATURITY_DATE": "20-03-2029",
            "STATUS": "ACTIVE",
            "PRODUCT": "MIDDLE WEALTH PLAN",
            "CLIENT": "YAW MENSAH",
            "PREMIUM": "125",
            "Date_of_Birth": "10-10-1985",
            "Gender": "Male",
            "Marital_Status": "Married",
            "Phone_Number": "0245566778",
            "ID_No": "GHA-1230987654-321",
            "ID_Type": "Ghana Card",
            "Residential_Address": "59 Coastline Ave, Tema, Ghana",
            "Postal_Address": "P.O. Box 1120, Tema, Ghana",
            "Email": "yaw.mensah@example.com",
            "Occupation": "Project Manager",
            "Policy_Term": "10 years",
            "Sum_Assured": "60000",
            "Payment_Frequency": "Bi-Annually"
        },
        {
            "PROPOSAL_NUMBER": "PSLP1005301310227160",
            "POLICY_NUMBER": "SLP1005301230227160",
            "ISSUE_DATE": "05-01-2020",
            "MATURITY_DATE": "05-01-2030",
            "STATUS": "ACTIVE",
            "PRODUCT": "STAR LIFE PLAN",
            "CLIENT": "JOYCE DANKWA",
            "PREMIUM": "220",
            "Date_of_Birth": "25-12-1979",
            "Gender": "Female",
            "Marital_Status": "Single",
            "Phone_Number": "0246677889",
            "ID_No": "GHA-4561237890-234",
            "ID_Type": "Ghana Card",
            "Residential_Address": "21 Harmony Rd, Kumasi, Ghana",
            "Postal_Address": "P.O. Box 3344, Kumasi, Ghana",
            "Email": "joyce.dankwa@example.com",
            "Occupation": "Architect",
            "Policy_Term": "10 years",
            "Sum_Assured": "75000",
            "Payment_Frequency": "Monthly"
        },
        {
            "PROPOSAL_NUMBER": "PCPP1005301320227161",
            "POLICY_NUMBER": "CPP1005301230227161",
            "ISSUE_DATE": "10-06-2022",
            "MATURITY_DATE": "10-06-2032",
            "STATUS": "ACTIVE",
            "PRODUCT": "CHILD PROTECTION PLAN",
            "CLIENT": "ABENA KUSI",
            "PREMIUM": "80",
            "Date_of_Birth": "01-01-1991",
            "Gender": "Female",
            "Marital_Status": "Single",
            "Phone_Number": "0244433221",
            "ID_No": "GHA-1112223334-555",
            "ID_Type": "Ghana Card",
            "Residential_Address": "34 Seaside Dr, Sekondi, Ghana",
            "Postal_Address": "P.O. Box 9987, Sekondi, Ghana",
            "Email": "abena.kusi@example.com",
            "Occupation": "Graphic Designer",
            "Policy_Term": "10 years",
            "Sum_Assured": "15000",
            "Payment_Frequency": "Quarterly"
        },
        {
            "PROPOSAL_NUMBER": "PWPP1005301330227162",
            "POLICY_NUMBER": "WPP1005301230227162",
            "ISSUE_DATE": "01-12-2018",
            "MATURITY_DATE": "01-12-2028",
            "STATUS": "ACTIVE",
            "PRODUCT": "WOMEN PROTECTION PLAN",
            "CLIENT": "FATI SULEIMAN",
            "PREMIUM": "95",
            "Date_of_Birth": "30-03-1987",
            "Gender": "Female",
            "Marital_Status": "Married",
            "Phone_Number": "0243344556",
            "ID_No": "GHA-7890123456-789",
            "ID_Type": "Ghana Card",
            "Residential_Address": "12 Lake View, Bolgatanga, Ghana",
            "Postal_Address": "P.O. Box 4321, Bolgatanga, Ghana",
            "Email": "fati.suleiman@example.com",
            "Occupation": "Police Officer",
            "Policy_Term": "10 years",
            "Sum_Assured": "35000",
            "Payment_Frequency": "Annually"
        },
        {
            "PROPOSAL_NUMBER": "PHPP1005401340227163",
            "POLICY_NUMBER": "HPP1005401230227163",
            "ISSUE_DATE": "15-04-2023",
            "MATURITY_DATE": "15-04-2033",
            "STATUS": "ACTIVE",
            "PRODUCT": "HEALTH PROTECTION PLAN",
            "CLIENT": "KOJO ASANTE",
            "PREMIUM": "105",
            "Date_of_Birth": "25-06-1982",
            "Gender": "Male",
            "Marital_Status": "Married",
            "Phone_Number": "0249988776",
            "ID_No": "GHA-4567890123-456",
            "ID_Type": "Ghana Card",
            "Residential_Address": "45 Pine Rd, Ho, Ghana",
            "Postal_Address": "P.O. Box 5678, Ho, Ghana",
            "Email": "kojo.asante@example.com",
            "Occupation": "Accountant",
            "Policy_Term": "10 years",
            "Sum_Assured": "40000",
            "Payment_Frequency": "Bi-Annually"
        },
        {
            "PROPOSAL_NUMBER": "PLMP1005401350227164",
            "POLICY_NUMBER": "LMP1005401230227164",
            "ISSUE_DATE": "30-11-2015",
            "MATURITY_DATE": "30-11-2025",
            "STATUS": "MATURED",
            "PRODUCT": "LONGTERM MASTER PLAN",
            "CLIENT": "AMA OSEI",
            "PREMIUM": "300",
            "Date_of_Birth": "10-09-1975",
            "Gender": "Female",
            "Marital_Status": "Married",
            "Phone_Number": "0246677885",
            "ID_No": "GHA-3456721890-543",
            "ID_Type": "Ghana Card",
            "Residential_Address": "98 Blossom Rd, Cape Coast, Ghana",
            "Postal_Address": "P.O. Box 6789, Cape Coast, Ghana",
            "Email": "ama.osei@example.com",
            "Occupation": "Consultant",
            "Policy_Term": "10 years",
            "Sum_Assured": "80000",
            "Payment_Frequency": "Monthly"
        }
       
    ]

